version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # For live-reloading in dev only
    networks:
      - scanner-network
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # For live-reloading in dev only
    networks:
      - scanner-network
    depends_on:
      - backend

networks:
  scanner-network:
    driver: bridge
